export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        /* APIS V1 palette — use sparingly; primary/semantic tokens first */
        ink: {
          DEFAULT: '#17201F',
          mid: '#202B29',
          soft: '#2B3835',
        },
        paper: {
          DEFAULT: '#F7F4EC',
          mid: '#EEEADF',
          deep: '#E2DDCF',
        },
        teal: {
          deep: '#176B63',
          DEFAULT: '#1F8176',
          bright: '#2C9589',
        },
        amber: {
          DEFAULT: '#B87524',
          bright: '#CE8B32',
          soft: '#F5E5CA',
        },
        success: '#397A5B',
        warning: '#B87524',
        danger: '#B84A43',
        info: '#39747A',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Space Grotesk', 'Inter', 'sans-serif'],
        hero: ['Space Grotesk', 'Inter', 'sans-serif'],
        condensed: ['Barlow Condensed', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        ikaros: ['Ikaros', 'Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
