import { motion } from 'framer-motion';
import { Scale, CheckCircle2, AlertTriangle, ArrowLeft, BookOpen } from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { useNavigate } from 'react-router-dom';

const TermsOfUse = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen pt-24 pb-32 px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-3xl mx-auto"
      >
        <Button 
          variant="ghost" 
          onClick={() => navigate(-1)}
          className="mb-8 text-muted-foreground hover:text-white"
        >
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>

        <header className="mb-12">
          <div className="w-16 h-16 rounded-2xl bg-secondary/20 flex items-center justify-center mb-6 border border-secondary/30">
            <Scale className="w-8 h-8 text-secondary" />
          </div>
          <h1 className="text-4xl md:text-5xl font-black mb-4">Terms of Use</h1>
          <p className="text-xl text-muted-foreground font-medium">The social contract of APIS AI.</p>
        </header>

        <div className="space-y-12 prose prose-invert max-w-none">
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <CheckCircle2 className="w-6 h-6 text-emerald-400" /> Usage Rights
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              APIS AI is provided as a sophisticated academic management tool. By using this platform, you agree to provide accurate academic information to ensure the integrity of the SGPA intelligence engine. You are responsible for maintaining the security of your authenticated session.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-primary" /> Academic Responsibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The insights generated by APIS AI are intended for self-improvement and planning purposes only. They do not constitute official academic records. Always verify your results with your official institution's portal.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <AlertTriangle className="w-6 h-6 text-amber-400" /> Service Limitations
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              While we prioritize 99.9% uptime and offline-first resilience, APIS AI is provided "as is." We are not liable for any data loss resulting from unauthorized account access or local device failures. We strongly encourage regular use of our <strong>Secure Backup</strong> feature.
            </p>
          </section>

          <section className="p-8 rounded-3xl bg-white/5 border border-white/10">
            <h3 className="text-xl font-bold mb-2">Platform Continuity</h3>
            <p className="text-sm text-muted-foreground">
              We reserve the right to refine platform features to maintain operational maturity. Any significant changes to the service terms will be communicated with the same clarity as our engineering principles.
            </p>
            <p className="text-xs text-muted-foreground mt-6 font-black uppercase tracking-widest">
              Last Updated: May 2026 • Version 1.2.0 (RC)
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default TermsOfUse;
